services:
  # << Microservice - Condig >>
  microservice-config:
    container_name: mcsv-config
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-config
    expose:
      - 8888
    ports:
      - 8888:8888
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # << Microservice - Eureka >>
  microservice-eureka:
    container_name: mcsv-eureka
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-eureka
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - microservice-config
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # << Microservice - Otros >>
  microservice-connector:
    container_name: mcsv-connector
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-connector
    expose:
      - 8090
    ports:
      - 8090:8090
    depends_on:
      - microservice-config
      - microservice-eureka
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  microservice-gateway:
    container_name: mcsv-gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-gateway
    expose:
      - 3761
    ports:
      - 3761:3761
    depends_on:
      - microservice-config
      - microservice-eureka
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  microservice-identity:
    container_name: mcsv-identity
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-identity
    expose:
      - 8091
    ports:
      - 8091:8091
    depends_on:
      - microservice-config
      - microservice-eureka
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  microservice-logs:
    container_name: mcsv-logs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-logs
    expose:
      - 8095
    ports:
      - 8095:8095
    environment:
      MONGODB_USER: <myUser>
      MONGODB_PASSWORD: <myPass>
    depends_on:
      - microservice-config
      - microservice-eureka
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  microservice-validation:
    container_name: mcsv-validation
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROSERVICE: microservice-validation
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - microservice-config
      - microservice-eureka
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

#networks:
#  spring-cloud-network:
#    driver: bridge