server:
  port: 3761

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/**
        - id: validation
          uri: 'http://localhost:9090'
          predicates:
            - Path=/broker/api/**

eureka:
  client:
    register-with-eureka: false
