server:
  port: 3761

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: 'http://localhost:8091'
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: false
