server:
  port: 8090

spring:
  application:
    name: msvc-connector

feign:
  okhttp:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka