server:
  port: 3761

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: validation
          uri: 'http://${HOST_NAME_VALIDATION}:9090'
          predicates:
            - Path=/broker/api/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: 'http://${HOST_NAME_IDENTITY}:8091'
          predicates:
            - Path=/broker/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            exposedHeaders:
              - Authorization
            allowedCredentials: false
            maxAge: 3600

      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      logging:
          level:
            org.springframework.web.cors: DEBUG

eureka:
  client:
    register-with-eureka: false
