broker:
  logs:
    debug: true

server:
  port: 9090

spring:
  application:
    name: msvc-validation

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka