broker:
  logs:
    debug: true

server:
  port: 9090

spring:
  application:
    name: msvc-validation

eureka:
  instance:
    hostname: ${HOST_NAME_VALIDATION}
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka