server:
  port: 8095

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/DBPB

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka