server:
  port: 8090

spring:
  application:
    name: msvc-connector

feign:
  okhttp:
    enabled: true

eureka:
  instance:
    hostname: ${HOST_NAME_CONNECTOR}
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka