server:
  port: 8091

spring:
  application:
    name: identity-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    appname: identity-service
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
