server:
  port: 3761

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: validation
          uri: 'http://${HOST_NAME_VALIDATION}:9090'
          predicates:
            - Path=/broker/api/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: 'http://${HOST_NAME_IDENTITY}:8091'
          predicates:
            - Path=/broker/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://192.168.56.1:4002"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "Authorization, Content-Type"
            exposedHeaders: "Authorization"
            allowedCredentials: true
            maxAge: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${HOST_EUREKA}:8761/eureka/
