server:
  port: 8091

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceidentity
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-adress}:${server.port}
    appname: identity-service
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
