server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ${HOST_EUREKA}
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka/